apiVersion : apps/v1
kind: Deployment
metadata:
  name: "appclstr-4928"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "appclstr-4928"
  template:
    metadata:
      labels:
        app: "appclstr-4928"
    spec:
      containers:
        - name: "appclstr-4928"
          image: "aksrgstry.azurecr.io/appclstr"
          ports:
          - containerPort: 80