apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kbctl-6317"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kbctl-6317"
  template:
    metadata:
      labels:
        app: "kbctl-6317"
    spec:
      containers:
        - name: "kbctl-6317"
          image: "crmwebui20210821173220.azurecr.io/kbctl"
          ports:
          - containerPort: 80