on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n appcrmclstrrgstry -g appcrmclstrrgstrya68d-rg --location "Central US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n appcrmclstrrgstry --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n appcrmclstrrgstry --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n appcrmclstrrgstry --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: appcrmclstrrgstry.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/CRM.WEBUI" -f  "CRM.WEBUI/Dockerfile" -t appcrmclstrrgstry.azurecr.io/crmclstr:${{ github.sha }} --label dockerfile-path=CRM.WEBUI/Dockerfile
        docker push appcrmclstrrgstry.azurecr.io/crmclstr:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_crmclstr_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep crmclstrbea5 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace crmclstrbea5`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: crmclstrbea5
        container-registry-url: appcrmclstrrgstry.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: crmclstrdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: crmclstrbea5
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          appcrmclstrrgstry.azurecr.io/crmclstr:${{ github.sha }}
        imagepullsecrets: |
          crmclstrdockerauth   
