on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: appcrmctnr.azurecr.io
        username: ${{ secrets.acr_appcrmctnr_username }}
        password: ${{ secrets.acr_appcrmctnr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/CRM.WEBUI" -f  "CRM.WEBUI/Dockerfile" -t appcrmctnr.azurecr.io/appclstr:${{ github.sha }} --label dockerfile-path=CRM.WEBUI/Dockerfile
        docker push appcrmctnr.azurecr.io/appclstr:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_appclstr_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep appclstr92e1 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace appclstr92e1`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: appclstr92e1
        container-registry-url: appcrmctnr.azurecr.io
        container-registry-username: ${{ secrets.acr_appcrmctnr_username }}
        container-registry-password: ${{ secrets.acr_appcrmctnr_password }}
        secret-name: appclstrdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: appclstr92e1
        manifests: |
          manifests/deployment-5.yml
          manifests/service-5.yml
        images: |
          appcrmctnr.azurecr.io/appclstr:${{ github.sha }}
        imagepullsecrets: |
          appclstrdockerauth
