on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aksrgstry.azurecr.io
        username: ${{ secrets.acr_aksrgstry_username }}
        password: ${{ secrets.acr_aksrgstry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/CRM.WEBUI" -f  "CRM.WEBUI/Dockerfile" -t aksrgstry.azurecr.io/appclstr:${{ github.sha }} --label dockerfile-path=CRM.WEBUI/Dockerfile
        docker push aksrgstry.azurecr.io/appclstr:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_appclstr_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep appclstr89c7 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace appclstr89c7`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: appclstr89c7
        container-registry-url: aksrgstry.azurecr.io
        container-registry-username: ${{ secrets.acr_aksrgstry_username }}
        container-registry-password: ${{ secrets.acr_aksrgstry_password }}
        secret-name: appclstrdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: appclstr89c7
        manifests: |
          manifests/deployment-3.yml
          manifests/service-3.yml
        images: |
          aksrgstry.azurecr.io/appclstr:${{ github.sha }}
        imagepullsecrets: |
          appclstrdockerauth
