on: [push]

# Environment variables available to all jobs and steps in this workflow

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    # Connect to Azure Container Registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: appcrmctnr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Container build and push to a Azure Container Registry (ACR)
    - run: |
       #docker build . -t appcrmctnr.azurecr.io/crmapp:${{ github.sha }}
       #docker build https://github.com/Anshumanjhs/CRM#master:CRMWEBUI
       docker build https://github.com/docker/rootfs.git#master:CRMWEBUI
       docker push appcrmctnr.azurecr.io/crmapp:${{ github.sha }}
    
    # Set the target Azure Kubernetes Service (AKS) cluster. 
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: appclstr
        resource-group: Wp-RG
    
    # Create namespace if doesn't exist
    - run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run -o json | kubectl apply -f -
    
    # Create image pull secret for ACR
    - uses: azure/k8s-create-secret@v1
      with:
        container-registry-url: appcrmctnr.azurecr.io
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: crm
        namespace: namespace-name
        force: true
    
    # Deploy app to AKS
    - uses: azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          appcrmctnr.azurecr.io/crmapp:${{ github.sha }}
        imagepullsecrets: |
          crm
        namespace: namespace-name











