on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: appcrmctnr.azurecr.io
        username: ${{ secrets.acr_appcrmctnr_username }}
        password: ${{ secrets.acr_appcrmctnr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/CRM.WEBUI" -f  "CRM.WEBUI/Dockerfile" -t appcrmctnr.azurecr.io/crmclstr:${{ github.sha }} --label dockerfile-path=CRM.WEBUI/Dockerfile
        docker push appcrmctnr.azurecr.io/crmclstr:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_crmclstr_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep crmclstr8e2d | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace crmclstr8e2d`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: crmclstr8e2d
        container-registry-url: appcrmctnr.azurecr.io
        container-registry-username: ${{ secrets.acr_appcrmctnr_username }}
        container-registry-password: ${{ secrets.acr_appcrmctnr_password }}
        secret-name: crmclstrdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: crmclstr8e2d
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          appcrmctnr.azurecr.io/crmclstr:${{ github.sha }}
        imagepullsecrets: |
          crmclstrdockerauth
